### ISSUE TITLE
UHD Firmware support for ANTSDR E310

### ISSUE THREAD

**Issue by r4d10n** [MicroPhase/antsdr_uhd#48]
I have been trying to get UHD working on Antsdr E310. 

I'd seen some references in Twitter abt UHD support for E310. I also saw some deleted references to Antsdr E310v2, which I believe is a different device (Zynq speed grade 2?). 

Can any update be provided on the support status for E310 ? If any pointers could be provided for adding the support, we can attempt doing the same.

**Comment by lone-boy** [comment]
Yes, E310 does not support uhd, E310v2 supports uhd

**Comment by meowdead** [comment]
biggest hardware difference is only speed grade? can we reball new zynq and use uhd with some patches?

**Comment by lone-boy** [comment]
> biggest hardware difference is only speed grade? can we reball new zynq and use uhd with some patches?

The old version of E310 has some problems when we try to transplant it, so we released the new version

**Comment by meowdead** [comment]
And now old E310 just a useless clone of pluto? Or you can provide more info?

**Comment by lone-boy** [comment]
> 
Yes, the old E310 only supports pluto, if you need to support uhd, it's a lot of work

**Comment by black-pigeon** [comment]
@meowdead, @r4d10n The old E310's ethernet is at ZYNQ PS side, while E200 and E310V2 is at PL side.  Thus we can do something like udp offload to PL to improve the performance. 
This difference in hardware architecture allows for different approaches to handling Ethernet traffic.

**Comment by meowdead** [comment]
Maybe remapping in project for GPIOA and external RTL8211F\marvell phy can be used? on the same BANK35

**Comment by uptools** [comment]
@black-pigeon   If using E310 as UHD with very little ethernet traffic, or running the application directly in the zynq, then low performance ethernet would not be needed.

Could we adapt uhd for E310 in those cases?

**Comment by black-pigeon** [comment]
Yes, it is possible, but these features are not available in our repository. You may need to implement PS-PL data interaction and write corresponding Linux kernel modules yourself. In fact, you can refer to the [RFNoC](https://github.com/EttusResearch/meta-ettus) implementation of Ettus [USRP E310](https://github.com/EttusResearch/uhd/tree/master/fpga/usrp3/top/e31x), which is the most similar device to AntSDR E310. Unfortunately, we do not  have any plans to implement RFNoC currently.
