### ISSUE TITLE
creating boot sd card

### ISSUE THREAD

**Issue by uptools** [MicroPhase/antsdr_uhd#49]
I copied all files from build_sdimg.zip
(downloaded from  https://github.com/MicroPhase/antsdr_uhd/releases/tag/v1.0)
to a fat32 sd card, but antsdr E310v2 does not boot from it nor it does anything after powering on with that card.

Is anything else needed to do on that card in order to be recognized?

The device does recognize and boot from the original SD card holding the pluto/iio firmware, but does nothing when powered on with the sd holding the uhd firmware.

**Comment by black-pigeon** [comment]
Sorry, the release file doesn't contain the firmware for e310v2, we will upload it latter.

**Comment by uptools** [comment]
OK, We re looking forward for it.

Is the current source, ok for regenerating it here? or it is only for prior versions?

**Comment by black-pigeon** [comment]
You can build firmware from source, which is only lacking optimized timing compared to our official release.

**Comment by lone-boy** [comment]
> OK, We re looking forward for it.
> 
> Is the current source, ok for regenerating it here? or it is only for prior versions?
Hi the link for the e310v2 firmware is below:
https://github.com/MicroPhase/antsdr_uhd/releases/download/v1.0/e310v2.zip
