### ISSUE TITLE
unzip fails on Windows.

### ISSUE THREAD

**Issue by gvanem** [MicroPhase/antsdr_uhd#51]
Just a little FYI folks.

I'm on Windows-10 and downloaded this repository as `antsdr_uhd-master.zip` file. But the name of these files:
```c
  firmware/linux/drivers/gpu/drm/nouveau/nvkm/subdev/i2c/aux.c
  firmware/linux/include/soc/arc/aux.h
``` 

caused `unzip antsdr_uhd-master.zip` to fail in creating the above files.
Similar problem with `7z x antsdr_uhd-master.zip`. But it wisely renamed `aux.[ch]` to `_aux.[ch]`.

A stupid Windows issue (coming from the age of MSDOS). Such names are still illegal on Windows! 
I'm not seeking to build your stuff on Windows (possible?). Just study the source. Hence this issue.

Besides there are these files with different casing:
```
firmware\linux\include\uapi\linux\netfilter\xt_CONNMARK.h
firmware\linux\include\uapi\linux\netfilter\xt_connmark.h
```

Why?

**Comment by lone-boy** [comment]
I'm very sorry, I usually use the git command to pull and download this warehouse. Generally speaking, this problem will not occur. There is no problem in building the image of this project under Windows through this source code.
