### ISSUE TITLE
Ettus UHD and AntSDR UHD

### ISSUE THREAD

**Issue by RFNOD** [MicroPhase/antsdr_uhd#52]
Hi,

Is it possible to merge the latest UHD-4.4 with the ANTSDR UHD to allow the use of an X310 and the AntSDR on the same box?

**Comment by black-pigeon** [comment]
Hello, our git repository only adds new sdr devices based on Ettus' UHD repository, and it won't affect the usage of official Ettus USRP devices. UHD4-4 is a possibility, and we may consider updating to that version at some point in the future.
