### ISSUE TITLE
Setting IP address in SD card boot mode?

### ISSUE THREAD

**Issue by tomtastic** [MicroPhase/antsdr_uhd#55]
The [documentation](https://antsdr-doc-en.readthedocs.io/en/latest/app_notes/set_the_iio_firmware_ip.html#sd-card-boot-mode) says "_is the same as starting and changing ip by qspi_", but both `fw_printenv` and `fw_setenv` fail :

```
# cat /etc/os-release
NAME=Buildroot
VERSION=v1.0-29-g627fa1ced
ID=buildroot
VERSION_ID=2020.02.8
PRETTY_NAME="Buildroot 2020.02.8"
```
```
# fw_printenv -n ipaddr_eth
Cannot open /dev/mtd1: No such file or directory
```
```
# fw_setenv ipaddr_eth 192.168.2.1
Cannot open /dev/mtd1: No such file or directory
Error: environment not initialized
```

**Comment by lone-boy** [comment]
Hello, this is the case. If your sd card has pluto firmware, it can be set in this way. The default factory sd card is uhd firmware, so to set the ip, you need to use a format such as ip_set 192.168.2.1.

**Comment by tomtastic** [comment]
Thanks, thats very helpful.
```data
# ip_set 192.168.2.10
/** write ip length succeed **/
/** write ip succeed **/
```
```data
# strings /sys/bus/i2c/devices/0-0050/eeprom
E200  v1
192.168.2.10
```
