### ISSUE TITLE
AntSDR UHD firmware e310v2 stuck on boot

### ISSUE THREAD

**Issue by parlotto** [MicroPhase/antsdr_uhd#64]
Hi,
I have an E310 (v2 I suppose since it has 10M/PPS input) that work perfectly with pluto firmware.
I would like to use uhd instead. But when I boot on SD made by the firmware download from 
 https://github.com/MicroPhase/antsdr_uhd/releases/download/v1.0/e310v2.zip
nothing is displayed on the console.
I can boot corectly on the same SD card with iio firmware.
Any help welcome.

**Comment by lone-boy** [comment]
Hello, you may have bought an E310. If possible, take a photo of the device and have a look.

**Comment by parlotto** [comment]
Hello, Thank you for answer. This is a photo of my item. Serial number is SN22A114XX
![IMG_20240129_110503](https://github.com/MicroPhase/antsdr_uhd/assets/14200538/ece0adc4-915a-42ec-8cb2-0c4cb6f6255a)

**Comment by lone-boy** [comment]
I think this is the new version of E310, not E310v2.

**Comment by parlotto** [comment]
ok, if it is the case, It is  possible to run UHD firmware ?

**Comment by lone-boy** [comment]
If it is E310, we currently do not have firmware adapted to run UHD.
