### ISSUE TITLE
E200 clock=external srsRAN_4G error

### ISSUE THREAD

**Issue by 555jones** [MicroPhase/antsdr_uhd#86]
Trying to use external 10MHz clock but always get the error:

**/usr/src/srsRAN_4G/lib/src/phy/rf/rf_uhd_imp.cc:833: Could not lock reference clock source. Sensor: ref_locked=false**

I am pretty sure this is the correct switch with srsue
device_args =  clock=external

Can anyone comment on using a 10MHz reference?

![2024-10-20 10_22_19-screen jpg - Windows Photo Viewer](https://github.com/user-attachments/assets/300da7be-12ac-4c3c-87a4-b2012b07cdc6)

**Comment by 0x657373656C6C** [comment]
Have you had any success with an external reference on the E200? I am using Leo Bodnar and have had no luck on UHD or IIO.

Microphase: Either comment with instructions or I am returning this junk device to you.

**Comment by 555jones** [comment]
@0x657373656C6C No response, I ended up buying a B210. There was a change made to firmware to reassign the input if the ext clock to the correct pin. It could very well be easily fixed but is a let down. Be great if there was a comment from @lone-boy or @black-pigeon on this matter. 

I have two ANTSDR devices sitting here...

**Comment by lone-boy** [comment]
usrp->set_clock_source("external");

    std::vector<std::string> sensor_names = usrp->get_mboard_sensor_names();
    if (std::find(sensor_names.begin(), sensor_names.end(), "ref_locked")
        != sensor_names.end()) {
        std::cout << "Waiting for reference lock..." << std::flush;
        bool ref_locked = false;
        for (int i = 0; i < 30 and not ref_locked; i++) {
            ref_locked = usrp->get_mboard_sensor("ref_locked", 0).to_bool();
            if (not ref_locked) {
                std::cout << "." << std::flush;
                std::this_thread::sleep_for(std::chrono::seconds(1));
            }
        }
        if (ref_locked) {
            std::cout << "LOCKED" << std::endl;
        } else {
            std::cout << "FAILED" << std::endl;
            std::cout << "Failed to lock to GPSDO 10 MHz Reference. Exiting."
                      << std::endl;
            exit(EXIT_FAILURE);
        }
    } else {
        std::cout << boost::format(
                "ref_locked sensor not present on this board.\n");
    }
    
    In this environment, I added a 10M clock and found that it can be locked.

**Comment by lone-boy** [comment]
```c++
usrp->set_clock_source("external");

std::vector<std::string> sensor_names = usrp->get_mboard_sensor_names();
if (std::find(sensor_names.begin(), sensor_names.end(), "ref_locked")
  != sensor_names.end()) {
  std::cout << "Waiting for reference lock..." << std::flush;
  bool ref_locked = false;
  for (int i = 0; i < 30 and not ref_locked; i++) {
      ref_locked = usrp->get_mboard_sensor("ref_locked", 0).to_bool();
      if (not ref_locked) {
          std::cout << "." << std::flush;
          std::this_thread::sleep_for(std::chrono::seconds(1));
      }
  }
  if (ref_locked) {
      std::cout << "LOCKED" << std::endl;
  } else {
      std::cout << "FAILED" << std::endl;
      std::cout << "Failed to lock to GPSDO 10 MHz Reference. Exiting."
                << std::endl;
      exit(EXIT_FAILURE);
  }
} else {
  std::cout << boost::format(
          "ref_locked sensor not present on this board.\n");
}
```
In this environment, I added a 10M clock and found that it can be locked.
I also asked my colleagues, and the relevant fpga code has been uploaded to the master branch.

**Comment by lone-boy** [comment]
> Have you had any success with an external reference on the E200? I am using Leo Bodnar and have had no luck on UHD or IIO.
> 
> Microphase: Either comment with instructions or I am returning this junk device to you.

First of all, thank you very much for choosing E200, but due to our personal technical ability and team size, we can't respond quickly. If you are not satisfied with the product, I understand. Because the product itself only transplants the early version of IIO driver and the UHD driver that can transmit IQ, which only adds a certain playability to this product. At the same time, due to many reasons, the response speed cannot meet your needs, and we are very sorry for this. We are also working hard to update.
At present, regarding the IIO driver, we have added the v0.38 source code version to the master branch, but there is no release of the corresponding firmware. If you need it urgently, I will first release the img of the sd card startup, or you can compile it yourself. All codes are open source.
Finally, regarding the return issue, you can find the way you purchased to consult and request related services.

**Comment by 555jones** [comment]
Thanks for the fast replay @lone-boy 
I copied the files to my sd card and retested but same issue as below.
Any ideas?

I tested the 10Mhz on my scope, it is working and also my B210, its working with ext ref.
Tried one brand new E200 and checked cable. 

![Screenshot from 2024-12-11 20-37-38](https://github.com/user-attachments/assets/7905d37b-b184-45e5-9f82-fa580141b3b4)
![Screenshot from 2024-12-11 20-47-10](https://github.com/user-attachments/assets/e58f0e18-faff-46d5-bf40-14dcf8804b15)

![3](https://github.com/user-attachments/assets/c839093e-2d42-457c-b1c7-69ed7c71902f)
![4](https://github.com/user-attachments/assets/94cdc480-d2e0-4c06-9a0b-3626ee4ef008)

**Comment by 0x657373656C6C** [comment]
Same here. I use the Leo Bodnar. 10MHz verified, cable good.

![image](https://github.com/user-attachments/assets/b833fbe9-fcad-47a6-8322-0bb64f4d1524)

**Comment by lone-boy** [comment]
[e200.zip](https://github.com/user-attachments/files/18120470/e200.zip)
Ok, please try this firmware
@555jones @0x657373656C6C

**Comment by 555jones** [comment]
@lone-boy @0x657373656C6C 
**Confirm that works.**

Tested with EXT_REF connected, it locked.
Disconnected it, and re-tested and it failed.

Whatever you did made it work!

Thank you very much.
What was the issue? I think it was an incorrect pin assignment?

![image](https://github.com/user-attachments/assets/d5488958-a667-4989-ae84-0acdb0816d34)

**Comment by 0x657373656C6C** [comment]
@lone-boy I can also confirm success having tested with srsLTE, OAI and OsmoBTS

**Comment by lone-boy** [comment]
> @lone-boy @0x657373656C6C **Confirm that works.**
> 
> Tested with EXT_REF connected, it locked. Disconnected it, and re-tested and it failed.
> 
> Whatever you did made it work!
> 
> Thank you very much. What was the issue? I think it was an incorrect pin assignment?
> 
> ![image](https://private-user-images.githubusercontent.com/149275000/395503702-d5488958-a667-4989-ae84-0acdb0816d34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDc2MTQsIm5iZiI6MTczNDM0NzMxNCwicGF0aCI6Ii8xNDkyNzUwMDAvMzk1NTAzNzAyLWQ1NDg4OTU4LWE2NjctNDk4OS1hZTg0LTBhY2RiMDgxNmQzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxMTA4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjIxZDk5NTgxYmE3NGE2YTUzN2M2N2IzMWE1N2Y3Mzc2ZTQ4MjMzY2FiOGIwOTc2MDMzZDc0YzNkMzUyMWU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZDMyMIJ_oGk2XG_2CMTVqxQoAS3WmLUasfaKYNFdCNY)

Hi, the problem was with locking the clock's buf, I think it's fixed now.

**Comment by 0x657373656C6C** [comment]
Any chance we can have that fix committed?

**Comment by lone-boy** [comment]
Hello, this problem has been fixed. You can use the above firmware or use the latest master branch to compile the firmware.
